[tool.aerich]
tortoise_orm = "src.settings.TORTOISE_ORM"
location = "./migrations"
src_folder = "./."

[project]
name = "vertice"
version = "0.1.0"
description = ""
authors = [
    {name = "Elibeth Curalli",email = "85085805+henrriusdev@users.noreply.github.com"}
]
license = {text = "MIT"}
readme = "README.md"
requires-python = ">=3.11,<4"
dependencies = [
    "aerich (==0.8.2)",
    "aiosqlite (==0.21.0)",
    "annotated-types (==0.7.0)",
    "anyio (==4.9.0)",
    "asyncclick (==8.1.8.0)",
    "blinker (==1.9.0)",
    "brotli (==1.1.0)",
    "cffi (==1.17.1)",
    "click (==8.1.8)",
    "colorama (==0.4.6)",
    "cssselect2 (==0.8.0)",
    "dictdiffer (==0.9.0)",
    "flask (==3.1.0)",
    "flask-cors (==5.0.1)",
    "flask-jwt-extended (==4.7.1)",
    "fonttools (==4.56.0)",
    "h11 (==0.14.0)",
    "html5lib (==1.1)",
    "httptools (==0.6.4)",
    "idna (==3.10)",
    "iso8601 (==2.1.0)",
    "itsdangerous (==2.2.0)",
    "jinja2 (==3.1.6)",
    "markupsafe (==3.0.2)",
    "packaging (==24.2)",
    "pillow (==11.1.0)",
    "psycopg (==3.2.6)",
    "psycopg-binary (==3.2.6)",
    "psycopg-pool (==3.2.6)",
    "psycopg2 (==2.9.10)",
    "pycparser (==2.22)",
    "pydantic (==2.11.1)",
    "pydantic-settings (==2.8.1)",
    "pydantic-core (==2.33.0)",
    "pydyf (==0.11.0)",
    "pyjwt (==2.10.1)",
    "pyphen (==0.17.2)",
    "pypika-tortoise (==0.5.0)",
    "python-dotenv (==1.1.0)",
    "pytz (==2025.2)",
    "pyyaml (==6.0.2)",
    "six (==1.17.0)",
    "sniffio (==1.3.1)",
    "tinycss2 (==1.4.0)",
    "tinyhtml5 (==2.0.0)",
    "tomlkit (==0.13.2)",
    "tortoise-orm (==0.24.2)",
    "typing-inspection (==0.4.0)",
    "typing-extensions (==4.13.0)",
    "tzdata (==2025.2)",
    "uvicorn (==0.34.0)",
    "watchfiles (==1.0.4)",
    "weasyprint (==65.0)",
    "webencodings (==0.5.1)",
    "websockets (==15.0.1)",
    "werkzeug (==3.1.3)",
    "zopfli (==0.2.3.post1)",
    "httpx (>=0.28.1,<0.29.0)",
    "num2words (>=0.5.14,<0.6.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
